version: '3'
services:
  api:
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - ./error.log:/usr/src/app/error.log
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
